export const PROFILES_LOADED = "PROFILES_LOADED";
export const PROFILES_ERROR = "PROFILES_ERROR";

export const HISTORY_LOADED = "HISTORY_LOADED";
export const HISTORY_ERROR = "HISTORY_ERROR";

export const TRANSFER_SUCCESS = "TRANSFER_SUCCESS";
export const TRANSFER_ERROR = "TRANSFER_ERROR";